services:
  function:
    container_name: function
    build:
      context: .
      dockerfile: function/Dockerfile
    ports:
      - 8080:8080
    environment:
      FUNCTION_TARGET: HelloWorld
    volumes:
      - ../:/app
    restart: always
